// Generated automatically by nearley
// http://github.com/Hardmath123/nearley
function id(x) {return x[0]; }


import { Toss } from "../../Toss.js";

function mirror( throws ){

   return throws.concat( throws.map( action => action.map( release => release.map(({ value, crossing }) => ({ value, crossing })) ).reverse() ));

}

function finalise( throws ){
  
   return throws.map( action => action.map((release, i) => release.map(toss => new Toss(toss.value, i, toss.crossing ? 1 - i : i))) );

}

var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "siteswap", "symbols": ["siteswap_a"], "postprocess": data => finalise(data[0])},
    {"name": "siteswap", "symbols": ["siteswap_s"], "postprocess": data => finalise(data[0])},
    {"name": "siteswap_a$macrocall$2$macrocall$2", "symbols": [{"literal":","}]},
    {"name": "siteswap_a$macrocall$2$macrocall$1$macrocall$2", "symbols": ["siteswap_a$macrocall$2$macrocall$2"]},
    {"name": "siteswap_a$macrocall$2$macrocall$1$macrocall$1", "symbols": ["toss_a"]},
    {"name": "siteswap_a$macrocall$2$macrocall$1$macrocall$1$ebnf$1$subexpression$1", "symbols": ["siteswap_a$macrocall$2$macrocall$1$macrocall$2", "toss_a"]},
    {"name": "siteswap_a$macrocall$2$macrocall$1$macrocall$1$ebnf$1", "symbols": ["siteswap_a$macrocall$2$macrocall$1$macrocall$1$ebnf$1$subexpression$1"]},
    {"name": "siteswap_a$macrocall$2$macrocall$1$macrocall$1$ebnf$1$subexpression$2", "symbols": ["siteswap_a$macrocall$2$macrocall$1$macrocall$2", "toss_a"]},
    {"name": "siteswap_a$macrocall$2$macrocall$1$macrocall$1$ebnf$1", "symbols": ["siteswap_a$macrocall$2$macrocall$1$macrocall$1$ebnf$1", "siteswap_a$macrocall$2$macrocall$1$macrocall$1$ebnf$1$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "siteswap_a$macrocall$2$macrocall$1$macrocall$1", "symbols": [{"literal":"["}, "toss_a", "siteswap_a$macrocall$2$macrocall$1$macrocall$1$ebnf$1", {"literal":"]"}], "postprocess": data => [data[1], ...data[2].map(el => el[1])]},
    {"name": "siteswap_a$macrocall$2$macrocall$1", "symbols": ["siteswap_a$macrocall$2$macrocall$1$macrocall$1"]},
    {"name": "siteswap_a$macrocall$2", "symbols": ["siteswap_a$macrocall$2$macrocall$1"]},
    {"name": "siteswap_a$macrocall$3", "symbols": [{"literal":","}]},
    {"name": "siteswap_a$macrocall$1$ebnf$1", "symbols": []},
    {"name": "siteswap_a$macrocall$1$ebnf$1$subexpression$1", "symbols": ["siteswap_a$macrocall$3", "siteswap_a$macrocall$2"]},
    {"name": "siteswap_a$macrocall$1$ebnf$1", "symbols": ["siteswap_a$macrocall$1$ebnf$1", "siteswap_a$macrocall$1$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "siteswap_a$macrocall$1", "symbols": ["siteswap_a$macrocall$2", "siteswap_a$macrocall$1$ebnf$1"], "postprocess": data => [data[0][0], ...data[1].map(m => m[1][0])]},
    {"name": "siteswap_a", "symbols": ["siteswap_a$macrocall$1"], "postprocess": id},
    {"name": "siteswap_a$macrocall$5$macrocall$2", "symbols": [{"literal":" "}]},
    {"name": "siteswap_a$macrocall$5$macrocall$1$macrocall$2", "symbols": ["siteswap_a$macrocall$5$macrocall$2"]},
    {"name": "siteswap_a$macrocall$5$macrocall$1$macrocall$1", "symbols": ["toss_a"]},
    {"name": "siteswap_a$macrocall$5$macrocall$1$macrocall$1$ebnf$1$subexpression$1", "symbols": ["siteswap_a$macrocall$5$macrocall$1$macrocall$2", "toss_a"]},
    {"name": "siteswap_a$macrocall$5$macrocall$1$macrocall$1$ebnf$1", "symbols": ["siteswap_a$macrocall$5$macrocall$1$macrocall$1$ebnf$1$subexpression$1"]},
    {"name": "siteswap_a$macrocall$5$macrocall$1$macrocall$1$ebnf$1$subexpression$2", "symbols": ["siteswap_a$macrocall$5$macrocall$1$macrocall$2", "toss_a"]},
    {"name": "siteswap_a$macrocall$5$macrocall$1$macrocall$1$ebnf$1", "symbols": ["siteswap_a$macrocall$5$macrocall$1$macrocall$1$ebnf$1", "siteswap_a$macrocall$5$macrocall$1$macrocall$1$ebnf$1$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "siteswap_a$macrocall$5$macrocall$1$macrocall$1", "symbols": [{"literal":"["}, "toss_a", "siteswap_a$macrocall$5$macrocall$1$macrocall$1$ebnf$1", {"literal":"]"}], "postprocess": data => [data[1], ...data[2].map(el => el[1])]},
    {"name": "siteswap_a$macrocall$5$macrocall$1", "symbols": ["siteswap_a$macrocall$5$macrocall$1$macrocall$1"]},
    {"name": "siteswap_a$macrocall$5", "symbols": ["siteswap_a$macrocall$5$macrocall$1"]},
    {"name": "siteswap_a$macrocall$6", "symbols": [{"literal":" "}]},
    {"name": "siteswap_a$macrocall$4$ebnf$1", "symbols": []},
    {"name": "siteswap_a$macrocall$4$ebnf$1$subexpression$1", "symbols": ["siteswap_a$macrocall$6", "siteswap_a$macrocall$5"]},
    {"name": "siteswap_a$macrocall$4$ebnf$1", "symbols": ["siteswap_a$macrocall$4$ebnf$1", "siteswap_a$macrocall$4$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "siteswap_a$macrocall$4", "symbols": ["siteswap_a$macrocall$5", "siteswap_a$macrocall$4$ebnf$1"], "postprocess": data => [data[0][0], ...data[1].map(m => m[1][0])]},
    {"name": "siteswap_a", "symbols": ["siteswap_a$macrocall$4"], "postprocess": id},
    {"name": "toss_a", "symbols": ["digit_a"], "postprocess": data => ({ value: data[0] })},
    {"name": "digit_a", "symbols": [/[0-9]/], "postprocess": data => Number(data[0])},
    {"name": "digit_a$ebnf$1", "symbols": [/[0-9]/]},
    {"name": "digit_a$ebnf$1", "symbols": ["digit_a$ebnf$1", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "digit_a", "symbols": [/[1-9]/, "digit_a$ebnf$1"], "postprocess": data => Number([data[0], ...data[1]].join(""))},
    {"name": "siteswap_s$ebnf$1$macrocall$2", "symbols": [{"literal":","}]},
    {"name": "siteswap_s$ebnf$1$macrocall$1$macrocall$2", "symbols": ["siteswap_s$ebnf$1$macrocall$2"]},
    {"name": "siteswap_s$ebnf$1$macrocall$1$macrocall$1", "symbols": ["toss_s"]},
    {"name": "siteswap_s$ebnf$1$macrocall$1$macrocall$1$ebnf$1$subexpression$1", "symbols": ["siteswap_s$ebnf$1$macrocall$1$macrocall$2", "toss_s"]},
    {"name": "siteswap_s$ebnf$1$macrocall$1$macrocall$1$ebnf$1", "symbols": ["siteswap_s$ebnf$1$macrocall$1$macrocall$1$ebnf$1$subexpression$1"]},
    {"name": "siteswap_s$ebnf$1$macrocall$1$macrocall$1$ebnf$1$subexpression$2", "symbols": ["siteswap_s$ebnf$1$macrocall$1$macrocall$2", "toss_s"]},
    {"name": "siteswap_s$ebnf$1$macrocall$1$macrocall$1$ebnf$1", "symbols": ["siteswap_s$ebnf$1$macrocall$1$macrocall$1$ebnf$1", "siteswap_s$ebnf$1$macrocall$1$macrocall$1$ebnf$1$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "siteswap_s$ebnf$1$macrocall$1$macrocall$1", "symbols": [{"literal":"["}, "toss_s", "siteswap_s$ebnf$1$macrocall$1$macrocall$1$ebnf$1", {"literal":"]"}], "postprocess": data => [data[1], ...data[2].map(el => el[1])]},
    {"name": "siteswap_s$ebnf$1$macrocall$1$macrocall$4", "symbols": ["siteswap_s$ebnf$1$macrocall$2"]},
    {"name": "siteswap_s$ebnf$1$macrocall$1$macrocall$3", "symbols": ["toss_s"]},
    {"name": "siteswap_s$ebnf$1$macrocall$1$macrocall$3$ebnf$1$subexpression$1", "symbols": ["siteswap_s$ebnf$1$macrocall$1$macrocall$4", "toss_s"]},
    {"name": "siteswap_s$ebnf$1$macrocall$1$macrocall$3$ebnf$1", "symbols": ["siteswap_s$ebnf$1$macrocall$1$macrocall$3$ebnf$1$subexpression$1"]},
    {"name": "siteswap_s$ebnf$1$macrocall$1$macrocall$3$ebnf$1$subexpression$2", "symbols": ["siteswap_s$ebnf$1$macrocall$1$macrocall$4", "toss_s"]},
    {"name": "siteswap_s$ebnf$1$macrocall$1$macrocall$3$ebnf$1", "symbols": ["siteswap_s$ebnf$1$macrocall$1$macrocall$3$ebnf$1", "siteswap_s$ebnf$1$macrocall$1$macrocall$3$ebnf$1$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "siteswap_s$ebnf$1$macrocall$1$macrocall$3", "symbols": [{"literal":"["}, "toss_s", "siteswap_s$ebnf$1$macrocall$1$macrocall$3$ebnf$1", {"literal":"]"}], "postprocess": data => [data[1], ...data[2].map(el => el[1])]},
    {"name": "siteswap_s$ebnf$1$macrocall$1", "symbols": [{"literal":"("}, "siteswap_s$ebnf$1$macrocall$1$macrocall$1", "siteswap_s$ebnf$1$macrocall$2", "siteswap_s$ebnf$1$macrocall$1$macrocall$3", {"literal":")"}], "postprocess": data => [data[1], data[3]]},
    {"name": "siteswap_s$ebnf$1", "symbols": ["siteswap_s$ebnf$1$macrocall$1"]},
    {"name": "siteswap_s$ebnf$1$macrocall$4", "symbols": [{"literal":","}]},
    {"name": "siteswap_s$ebnf$1$macrocall$3$macrocall$2", "symbols": ["siteswap_s$ebnf$1$macrocall$4"]},
    {"name": "siteswap_s$ebnf$1$macrocall$3$macrocall$1", "symbols": ["toss_s"]},
    {"name": "siteswap_s$ebnf$1$macrocall$3$macrocall$1$ebnf$1$subexpression$1", "symbols": ["siteswap_s$ebnf$1$macrocall$3$macrocall$2", "toss_s"]},
    {"name": "siteswap_s$ebnf$1$macrocall$3$macrocall$1$ebnf$1", "symbols": ["siteswap_s$ebnf$1$macrocall$3$macrocall$1$ebnf$1$subexpression$1"]},
    {"name": "siteswap_s$ebnf$1$macrocall$3$macrocall$1$ebnf$1$subexpression$2", "symbols": ["siteswap_s$ebnf$1$macrocall$3$macrocall$2", "toss_s"]},
    {"name": "siteswap_s$ebnf$1$macrocall$3$macrocall$1$ebnf$1", "symbols": ["siteswap_s$ebnf$1$macrocall$3$macrocall$1$ebnf$1", "siteswap_s$ebnf$1$macrocall$3$macrocall$1$ebnf$1$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "siteswap_s$ebnf$1$macrocall$3$macrocall$1", "symbols": [{"literal":"["}, "toss_s", "siteswap_s$ebnf$1$macrocall$3$macrocall$1$ebnf$1", {"literal":"]"}], "postprocess": data => [data[1], ...data[2].map(el => el[1])]},
    {"name": "siteswap_s$ebnf$1$macrocall$3$macrocall$4", "symbols": ["siteswap_s$ebnf$1$macrocall$4"]},
    {"name": "siteswap_s$ebnf$1$macrocall$3$macrocall$3", "symbols": ["toss_s"]},
    {"name": "siteswap_s$ebnf$1$macrocall$3$macrocall$3$ebnf$1$subexpression$1", "symbols": ["siteswap_s$ebnf$1$macrocall$3$macrocall$4", "toss_s"]},
    {"name": "siteswap_s$ebnf$1$macrocall$3$macrocall$3$ebnf$1", "symbols": ["siteswap_s$ebnf$1$macrocall$3$macrocall$3$ebnf$1$subexpression$1"]},
    {"name": "siteswap_s$ebnf$1$macrocall$3$macrocall$3$ebnf$1$subexpression$2", "symbols": ["siteswap_s$ebnf$1$macrocall$3$macrocall$4", "toss_s"]},
    {"name": "siteswap_s$ebnf$1$macrocall$3$macrocall$3$ebnf$1", "symbols": ["siteswap_s$ebnf$1$macrocall$3$macrocall$3$ebnf$1", "siteswap_s$ebnf$1$macrocall$3$macrocall$3$ebnf$1$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "siteswap_s$ebnf$1$macrocall$3$macrocall$3", "symbols": [{"literal":"["}, "toss_s", "siteswap_s$ebnf$1$macrocall$3$macrocall$3$ebnf$1", {"literal":"]"}], "postprocess": data => [data[1], ...data[2].map(el => el[1])]},
    {"name": "siteswap_s$ebnf$1$macrocall$3", "symbols": [{"literal":"("}, "siteswap_s$ebnf$1$macrocall$3$macrocall$1", "siteswap_s$ebnf$1$macrocall$4", "siteswap_s$ebnf$1$macrocall$3$macrocall$3", {"literal":")"}], "postprocess": data => [data[1], data[3]]},
    {"name": "siteswap_s$ebnf$1", "symbols": ["siteswap_s$ebnf$1", "siteswap_s$ebnf$1$macrocall$3"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "siteswap_s$ebnf$2", "symbols": [{"literal":"*"}], "postprocess": id},
    {"name": "siteswap_s$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "siteswap_s", "symbols": ["siteswap_s$ebnf$1", "siteswap_s$ebnf$2"], "postprocess": data => data[1] === null ? data[0] : mirror(data[0])},
    {"name": "siteswap_s$ebnf$3$macrocall$2", "symbols": [{"literal":" "}]},
    {"name": "siteswap_s$ebnf$3$macrocall$1$macrocall$2", "symbols": ["siteswap_s$ebnf$3$macrocall$2"]},
    {"name": "siteswap_s$ebnf$3$macrocall$1$macrocall$1", "symbols": ["toss_s"]},
    {"name": "siteswap_s$ebnf$3$macrocall$1$macrocall$1$ebnf$1$subexpression$1", "symbols": ["siteswap_s$ebnf$3$macrocall$1$macrocall$2", "toss_s"]},
    {"name": "siteswap_s$ebnf$3$macrocall$1$macrocall$1$ebnf$1", "symbols": ["siteswap_s$ebnf$3$macrocall$1$macrocall$1$ebnf$1$subexpression$1"]},
    {"name": "siteswap_s$ebnf$3$macrocall$1$macrocall$1$ebnf$1$subexpression$2", "symbols": ["siteswap_s$ebnf$3$macrocall$1$macrocall$2", "toss_s"]},
    {"name": "siteswap_s$ebnf$3$macrocall$1$macrocall$1$ebnf$1", "symbols": ["siteswap_s$ebnf$3$macrocall$1$macrocall$1$ebnf$1", "siteswap_s$ebnf$3$macrocall$1$macrocall$1$ebnf$1$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "siteswap_s$ebnf$3$macrocall$1$macrocall$1", "symbols": [{"literal":"["}, "toss_s", "siteswap_s$ebnf$3$macrocall$1$macrocall$1$ebnf$1", {"literal":"]"}], "postprocess": data => [data[1], ...data[2].map(el => el[1])]},
    {"name": "siteswap_s$ebnf$3$macrocall$1$macrocall$4", "symbols": ["siteswap_s$ebnf$3$macrocall$2"]},
    {"name": "siteswap_s$ebnf$3$macrocall$1$macrocall$3", "symbols": ["toss_s"]},
    {"name": "siteswap_s$ebnf$3$macrocall$1$macrocall$3$ebnf$1$subexpression$1", "symbols": ["siteswap_s$ebnf$3$macrocall$1$macrocall$4", "toss_s"]},
    {"name": "siteswap_s$ebnf$3$macrocall$1$macrocall$3$ebnf$1", "symbols": ["siteswap_s$ebnf$3$macrocall$1$macrocall$3$ebnf$1$subexpression$1"]},
    {"name": "siteswap_s$ebnf$3$macrocall$1$macrocall$3$ebnf$1$subexpression$2", "symbols": ["siteswap_s$ebnf$3$macrocall$1$macrocall$4", "toss_s"]},
    {"name": "siteswap_s$ebnf$3$macrocall$1$macrocall$3$ebnf$1", "symbols": ["siteswap_s$ebnf$3$macrocall$1$macrocall$3$ebnf$1", "siteswap_s$ebnf$3$macrocall$1$macrocall$3$ebnf$1$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "siteswap_s$ebnf$3$macrocall$1$macrocall$3", "symbols": [{"literal":"["}, "toss_s", "siteswap_s$ebnf$3$macrocall$1$macrocall$3$ebnf$1", {"literal":"]"}], "postprocess": data => [data[1], ...data[2].map(el => el[1])]},
    {"name": "siteswap_s$ebnf$3$macrocall$1", "symbols": [{"literal":"("}, "siteswap_s$ebnf$3$macrocall$1$macrocall$1", "siteswap_s$ebnf$3$macrocall$2", "siteswap_s$ebnf$3$macrocall$1$macrocall$3", {"literal":")"}], "postprocess": data => [data[1], data[3]]},
    {"name": "siteswap_s$ebnf$3", "symbols": ["siteswap_s$ebnf$3$macrocall$1"]},
    {"name": "siteswap_s$ebnf$3$macrocall$4", "symbols": [{"literal":" "}]},
    {"name": "siteswap_s$ebnf$3$macrocall$3$macrocall$2", "symbols": ["siteswap_s$ebnf$3$macrocall$4"]},
    {"name": "siteswap_s$ebnf$3$macrocall$3$macrocall$1", "symbols": ["toss_s"]},
    {"name": "siteswap_s$ebnf$3$macrocall$3$macrocall$1$ebnf$1$subexpression$1", "symbols": ["siteswap_s$ebnf$3$macrocall$3$macrocall$2", "toss_s"]},
    {"name": "siteswap_s$ebnf$3$macrocall$3$macrocall$1$ebnf$1", "symbols": ["siteswap_s$ebnf$3$macrocall$3$macrocall$1$ebnf$1$subexpression$1"]},
    {"name": "siteswap_s$ebnf$3$macrocall$3$macrocall$1$ebnf$1$subexpression$2", "symbols": ["siteswap_s$ebnf$3$macrocall$3$macrocall$2", "toss_s"]},
    {"name": "siteswap_s$ebnf$3$macrocall$3$macrocall$1$ebnf$1", "symbols": ["siteswap_s$ebnf$3$macrocall$3$macrocall$1$ebnf$1", "siteswap_s$ebnf$3$macrocall$3$macrocall$1$ebnf$1$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "siteswap_s$ebnf$3$macrocall$3$macrocall$1", "symbols": [{"literal":"["}, "toss_s", "siteswap_s$ebnf$3$macrocall$3$macrocall$1$ebnf$1", {"literal":"]"}], "postprocess": data => [data[1], ...data[2].map(el => el[1])]},
    {"name": "siteswap_s$ebnf$3$macrocall$3$macrocall$4", "symbols": ["siteswap_s$ebnf$3$macrocall$4"]},
    {"name": "siteswap_s$ebnf$3$macrocall$3$macrocall$3", "symbols": ["toss_s"]},
    {"name": "siteswap_s$ebnf$3$macrocall$3$macrocall$3$ebnf$1$subexpression$1", "symbols": ["siteswap_s$ebnf$3$macrocall$3$macrocall$4", "toss_s"]},
    {"name": "siteswap_s$ebnf$3$macrocall$3$macrocall$3$ebnf$1", "symbols": ["siteswap_s$ebnf$3$macrocall$3$macrocall$3$ebnf$1$subexpression$1"]},
    {"name": "siteswap_s$ebnf$3$macrocall$3$macrocall$3$ebnf$1$subexpression$2", "symbols": ["siteswap_s$ebnf$3$macrocall$3$macrocall$4", "toss_s"]},
    {"name": "siteswap_s$ebnf$3$macrocall$3$macrocall$3$ebnf$1", "symbols": ["siteswap_s$ebnf$3$macrocall$3$macrocall$3$ebnf$1", "siteswap_s$ebnf$3$macrocall$3$macrocall$3$ebnf$1$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "siteswap_s$ebnf$3$macrocall$3$macrocall$3", "symbols": [{"literal":"["}, "toss_s", "siteswap_s$ebnf$3$macrocall$3$macrocall$3$ebnf$1", {"literal":"]"}], "postprocess": data => [data[1], ...data[2].map(el => el[1])]},
    {"name": "siteswap_s$ebnf$3$macrocall$3", "symbols": [{"literal":"("}, "siteswap_s$ebnf$3$macrocall$3$macrocall$1", "siteswap_s$ebnf$3$macrocall$4", "siteswap_s$ebnf$3$macrocall$3$macrocall$3", {"literal":")"}], "postprocess": data => [data[1], data[3]]},
    {"name": "siteswap_s$ebnf$3", "symbols": ["siteswap_s$ebnf$3", "siteswap_s$ebnf$3$macrocall$3"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "siteswap_s$ebnf$4", "symbols": [{"literal":"*"}], "postprocess": id},
    {"name": "siteswap_s$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "siteswap_s", "symbols": ["siteswap_s$ebnf$3", "siteswap_s$ebnf$4"], "postprocess": data => data[1] === null ? data[0] : mirror(data[0])},
    {"name": "toss_s$ebnf$1", "symbols": ["crossing"], "postprocess": id},
    {"name": "toss_s$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "toss_s", "symbols": ["digit_s", "toss_s$ebnf$1"], "postprocess": data => ({ value: data[0], crossing: data[1] !== null })},
    {"name": "digit_s", "symbols": [/[02468]/], "postprocess": data => Number(data[0]) / 2},
    {"name": "digit_s$ebnf$1", "symbols": [/[02468]/]},
    {"name": "digit_s$ebnf$1", "symbols": ["digit_s$ebnf$1", /[02468]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "digit_s", "symbols": [/[2468]/, "digit_s$ebnf$1"], "postprocess": data => Number([data[0], ...data[1]].join("")) / 2},
    {"name": "crossing", "symbols": [{"literal":"x"}], "postprocess": id}
]
  , ParserStart: "siteswap"
}
export { grammar };
